### ISSUE TITLE
Error thrown and reported as requested

### ISSUE THREAD

**Issue by willemgons** [sergiisyrovatchenko/SQLIndexManager#30]
Application has encountered an unexpected error
Please send error detail to www.github.com/sergiisyrovatchenko/SQLIndexManager

SQL Server: SQL Server 2012 RTM (11.0.2100.60) (64-bit)
Build: 1.0.0.68

A severe error occurred on the current command.  The results, if any, should be discarded.
A severe error occurred on the current command.  The results, if any, should be discarded.
Warning: Null value is eliminated by an aggregate or other SET operation.
.Net SqlClient Data Provider
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping)
   at System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   at System.Data.Common.DataAdapter.Fill(DataSet dataSet, String srcTable, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at SQLIndexManager.QueryEngine.GetIndexes(SqlConnection connection)
   at SQLIndexManager.MainBox.ScanIndexes(Object sender, DoWorkEventArgs e)

**Comment by sergiisyrovatchenko** [comment]
Hi @willemgons 

Do you have stable network connection to the database server?
Please provide results of `DBCC CHECKDB('your_database_name')`.

Thanks!

**Comment by willemgons** [comment]
My aplogies. This was due to the fact that there were large NHibernate updates busy on 2 dbs that have tables as big as 14Gig. The job was run on a server that carries 56 dbs in total and I forgot to set the timeouts properly.
Amazing job BTW. I have been threatening this for years. This is gr8. All the best

**Comment by sergiisyrovatchenko** [comment]
Hi @willemgons

Thanks for your feedback! Have a nice day :)
